const fs = require('fs');

const code = [
  'import React, { useState, useEffect } from "react";',
  'import { LayoutDashboard, Cpu, KeyRound, ShieldAlert, Zap, Radio, Search, AlertTriangle, RefreshCw, Bell, User } from "lucide-react";',
  '',
  'export default function App() {',
  '  const [tab, setTab] = useState("overview");',
  '  const [attack, setAttack] = useState(false);',
  '  const [count, setCount] = useState(1248);',
  '',
  '  useEffect(() => {',
  '    const t = setInterval(() => setCount(p => p + (Math.random() > 0.5 ? 1 : -1)), 3000);',
  '    return () => clearInterval(t);',
  '  }, []);',
  '',
  '  const [devices, setDevices] = useState([',
  '    { id: "SNX-ESP32-0002", sku: "ESP32-WROOM-32D", ip: "10.50.250.175", status: "ACTIVE" },',
  '    { id: "SNX-ESP32-0004", sku: "ESP32-S3-DevKit", ip: "10.50.250.200", status: "ACTIVE" },',
  '    { id: "SNX-GW-RPI4-01", sku: "RPi 4 Model B", ip: "10.50.250.101", status: "ACTIVE" },',
  '    { id: "SNX-ESP32-0001", sku: "ESP32-C3-MINI", ip: "10.50.250.112", status: "REVOKED" }',
  '  ]);',
  '',
  '  const [logs, setLogs] = useState([',
  '    { id: 1, time: "18:24:12", type: "INFO", src: "AuthSphere-CA", msg: "Mutual TLS verified via ECC-secp256r1 (34ms)." },',
  '    { id: 2, time: "18:25:01", type: "INFO", src: "Mosquitto", msg: "Dynamic ACL applied for telemetry topics." }',
  '  ]);',
  '',
  '  const trigger = () => {',
  '    setAttack(true);',
  '    setDevices(d => d.map(x => x.id === "SNX-ESP32-0004" ? { ...x, status: "QUARANTINED" } : x));',
  '    setLogs(l => [{ id: Date.now(), time: new Date().toLocaleTimeString(), type: "CRITICAL", src: "Nakshatra-DLP", msg: "DLP LEAK: Credit card PAN found on SNX-ESP32-0004! Quarantined." }, ...l]);',
  '  };',
  '',
  '  const resolve = () => {',
  '    setAttack(false);',
  '    setDevices(d => d.map(x => x.id === "SNX-ESP32-0004" ? { ...x, status: "ACTIVE" } : x));',
  '    setLogs(l => [{ id: Date.now(), time: new Date().toLocaleTimeString(), type: "INFO", src: "AuthSphere-CA", msg: "Zero-Touch re-attestation passed. Node restored." }, ...l]);',
  '  };',
  '',
  '  const revoke = (id) => {',
  '    setDevices(d => d.map(x => x.id === id ? { ...x, status: "REVOKED" } : x));',
  '    setLogs(l => [{ id: Date.now(), time: new Date().toLocaleTimeString(), type: "CRITICAL", src: "AuthSphere-CA", msg: "Node " + id + " revoked and blacklisted." }, ...l]);',
  '  };',
  '',
  '  return (',
  '